spring.application.name=strivo-api
spring.datasource.url=jdbc:postgresql://localhost:5432/strivo
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update